version: "2.3"
services:

  blogapp:
    build: .
    container_name: blogapp
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0:8000"
    volumes:
     - ./blog:/blog
    ports:
     - "8000:8000"
    restart: unless-stopped
    #depends_on:
    # - blogappdb

  #blogappdb:
  #  image: postgres
  #  container_name: blogappdb
  #  environment:
  #    - POSTGRES_PASSWORD=102030
  #    - POSTGRES_USER=wand
  #    - POSTGRES_DB=todolist
  #  volumes:
  #    - blogapp-vol:/var/lib/postgresql/data
  #  ports:
  #    - "5432:5432"

  #volumes:
  #  blogapp-vol:
